package controllers;

public enum Command {
    ADD_PRODUCT,SEARCH_PRODUCT,DELETE_PRODUCT,EXIT,B_MENU,
    SAVE_PRODUCT,CANCEL_PRODUCT,MODIFY_PRODUCT,JD_DELETE_PRODUCT,
    DIALOG_DELETE,CANCEL_DELETE
}
